name: CD - Deploy to DeWeb

on:
  push:
    branches: [main, dev]

jobs:
  deploy-main:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    needs: ci # ← attend que le workflow ci.yml finisse
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist-main
          path: ./dist

      - name: Deploy Main → buildnet
        uses: massalabs/deweb-gh-action@v0.1.0
        with:
          config_file: ./deweb_cli_config.main.buildnet.json
          source_folder: ./dist
        env:
          MASSA_DEWEB_SECRET_KEY: ${{ secrets.PRIVATE_KEY }}

      - name: URL
        run: echo "Main deployed → ${{ steps.deploy.outputs.deployed-website }}"

  deploy-dev:
    if: github.ref_name == 'dev'
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist-dev
          path: ./dist

      - name: Deploy Dev → buildnet
        uses: massalabs/deweb-gh-action@v0.1.0
        with:
          config_file: ./deweb_cli_config.dev.buildnet.json
          source_folder: ./dist
        env:
          MASSA_DEWEB_SECRET_KEY: ${{ secrets.PRIVATE_KEY }}

      - name: URL
        run: echo "Dev deployed → ${{ steps.deploy.outputs.deployed-website }}"
