name: Deweb uploader

on:
  push:
    branches: [main, dev]

jobs:
  deweb:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        network: [buildnet]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Get short commit hash
        id: vars
        run: |
          echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build
        env:
          VITE_PROTOCOL_API_URL: ${{ secrets.VITE_PROTOCOL_API_URL }}
          VITE_APP_VERSION: ${{ env.COMMIT_HASH }}
        run: npm run build

      - name: Deploy main version to Massa DeWeb (${{ matrix.network }})
        if: github.ref_name == 'main'
        id: deploy
        uses: massalabs/deweb-gh-action@v0.1.0
        with:
          config_file: ./deweb_cli_config.main.${{ matrix.network }}.json
          source_folder: ./dist
        env:
          MASSA_DEWEB_SECRET_KEY: ${{ matrix.network == 'buildnet' && secrets.PRIVATE_KEY || secrets.MASSA_DEWEB_MAINNET_PKEY }}

      - name: Get deployed main website address on ${{ matrix.network }}
        if: github.ref_name == 'main'
        run: |
          echo "Deployed main website address on ${{ matrix.network }}: ${{ steps.deploy.outputs.deployed-website }}"

      - name: Deploy dev version to Massa DeWeb (${{ matrix.network }})
        if: github.ref_name == 'dev' && matrix.network == 'buildnet'
        id: deploy-dev
        uses: massalabs/deweb-gh-action@v0.1.0
        with:
          config_file: ./deweb_cli_config.dev.buildnet.json
          source_folder: ./dist
        env:
          MASSA_DEWEB_SECRET_KEY: ${{ matrix.network == 'buildnet' && secrets.PRIVATE_KEY || secrets.MASSA_DEWEB_MAINNET_PKEY }}

      - name: Get deployed dev website address on ${{ matrix.network }}
        if: github.ref_name == 'dev' && matrix.network == 'buildnet'
        run: |
          echo "Deployed dev website address on ${{ matrix.network }}: ${{ steps.deploy-dev.outputs.deployed-website }}"
